### ISSUE TITLE
[WebToolsE2E][Aspire] Getting some package downgrade errors when opening eShopOnAzure/eShop.Web solution.

### ISSUE THREAD

**Issue by v-sherryfan** [Azure-Samples/eShopOnAzure#27]
**REGRESSION INFO:** Worked on Aspire 8.0 Preview 5

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 6 [ Includes Aspire 8.0.0-preview.6.24214.1 and SDK 8.0.300-preview.24203.14 ]
3. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone eShopOnAzure repo, Checkout the `aspire-preview6` branch
2. Update sdk version to 8.0.300-preview.24203.14 in global.json
3. Open eShop.Web.slnf

**ACTUAL**
Warning As Error: Detected package downgrade: OpenTelemetry.Extensions.Hosting from 1.8.0 to 1.7.0. Reference the package directly from the project to select a different version.  eShop.ServiceDefaults -> Aspire.Azure.Messaging.ServiceBus 8.0.0-preview.6.24214.1 -> OpenTelemetry.Extensions.Hosting (>= 1.8.0)  eShop.ServiceDefaults -> OpenTelemetry.Extensions.Hosting (>= 1.7.0)

Warning As Error: Detected package downgrade: AspNetCore.HealthChecks.AzureServiceBus from 8.0.1 to 8.0.0. Reference the package directly from the project to select a different version.  EventBusServiceBus -> Aspire.Azure.Messaging.ServiceBus 8.0.0-preview.6.24214.1 -> AspNetCore.HealthChecks.AzureServiceBus (>= 8.0.1)  EventBusServiceBus -> AspNetCore.HealthChecks.AzureServiceBus (>= 8.0.0)

Detected package downgrade: OpenTelemetry.Extensions.Hosting from 1.8.0 to centrally defined 1.7.0. Update the centrally managed package version to a higher version.  Webhooks.API -> Aspire.Npgsql.EntityFrameworkCore.PostgreSQL 8.0.0-preview.6.24214.1 -> OpenTelemetry.Extensions.Hosting (>= 1.8.0)  Webhooks.API -> OpenTelemetry.Extensions.Hosting (>= 1.7.0)

Detected package downgrade: OpenTelemetry.Extensions.Hosting from 1.8.0 to centrally defined 1.7.0. Update the centrally managed package version to a higher version.  Webhooks.API -> Aspire.Azure.Messaging.ServiceBus 8.0.0-preview.6.24214.1 -> OpenTelemetry.Extensions.Hosting (>= 1.8.0)  Webhooks.API -> OpenTelemetry.Extensions.Hosting (>= 1.7.0)

![image](https://github.com/Azure-Samples/eShopOnAzure/assets/71361488/cb235779-26b6-4d09-a02e-c02f0bd48cb3)

**Note**

1. Manually updating the relevant package versions does not resolve these errors either.

**EXPECTED**

Opening and building solution without any errors.

**Comment by danmoseley** [comment]
I don't know why dependabot didn't open a PR to update `<PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.7.0" />` to 1.8.0 or 1.8.1. That will have to be manual/integrate from other eshop.

The other one does have a dependabot https://github.com/Azure-Samples/eShopOnAzure/pull/25

I do think in general it is probably easiest to merge dependabot PR's as they come in.

**Comment by balachir** [comment]
@adityamandaleeka @danmoseley I tried cloning the aspire-preview7 branch of this repo today. We're still seeing these package downgrade errors upon restore of eShop.Web.slnf. Should we open a separate issue to track these package downgrade errors for aspire P7? Please let us know.

cc: @v-sherryfan

**Comment by adityamandaleeka** [comment]
@balachir I'm seeing those too and will try to fix it soon. No new issue required.

**Comment by adityamandaleeka** [comment]
@balachir It should be fixed now.

**Comment by v-sherryfan** [comment]
Fixed in main branch (Aspire 8.0 P7)
