### ISSUE TITLE
Add Product LInk to chat experience..

### ISSUE THREAD

**Issue by denzilribeiro** [Azure-Samples/eShopOnAzure#33]
Chat gives great recommendations but lacks a product link to directly add to shopping bag . It adds the product description and even an image would be awesome to have a quick add to shopping bag or a link that goes to the product item individually so the user could explore more.

![image](https://github.com/Azure-Samples/eShopOnAzure/assets/12561620/ca42f077-252f-4730-9d4c-2378499f2d15)

**Comment by BrennanConroy** [comment]
Could you file this on https://github.com/dotnet/eshop? It's not specific to eShopOnAzure

**Comment by denzilribeiro** [comment]
Done: https://github.com/dotnet/eShop/issues/341
